// pages/api/generate-report.js

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).end("Only POST allowed");

  const { roast, jokes = [], advice = [], url } = req.body;

  const lines = [];

  lines.push(`# 🔥 Pro Roast Report`);
  lines.push(`**Website:** [${url}](${url})`);
  lines.push(``);
  lines.push(`## 👀 Brutal Roast`);
  lines.push(roast);
  lines.push(``);

  if (jokes.length > 0) {
    lines.push(`## 🤣 Roast Jokes`);
    jokes.forEach((joke) => lines.push(`- ${joke}`));
    lines.push(``);
  }

  lines.push(`## 🛠 Improvement Tips`);
  advice.forEach((tip, i) => lines.push(`${i + 1}. ${tip}`));
  lines.push(``);
  lines.push(`---`);
  lines.push(`_Report generated by **RoastBot.ai** using LLaMA 3.3 via Groq._`);

  const markdown = lines.join("\n");

  res.setHeader("Content-Type", "text/markdown; charset=utf-8");
  res.setHeader(
    "Content-Disposition",
    "attachment; filename=pro-roast-report.md"
  );
  res.status(200).send(markdown);
}
